version: '3'

services:

####################
# Setup Database container
####################

  db:
    build: ./backend/db
    volumes: 
      - ./backend/db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: api
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

####################
# Setup Api container
####################

  api:
    build: ./backend/api
    volumes: 
      - ./backend/api:/var/www/html/
    depends_on:
       - db
    restart: always
    ports:
      - "8000:80"
    links:
      - db:mysql    

####################
# Setup React container
####################

  app:
    build: ./frontend/app      
    ports:
      - 80:3000
    volumes:
      - ./frontend/app/src:/srv/app/src
      - ./frontend/app/public:/srv/app/public
    depends_on:
      - api
    links:
      - api
    restart: always
    command: npm run start
volumes:
    db_data:
