version: '3.3'

services:

####################
# Setup Database container
####################

  db:
    build: ./backend/db
    volumes: 
      - ./backend/db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: api
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

####################
# Setup Api container
####################

  api:
    build: ./backend/api
    volumes: 
      - ./backend/api:/var/www/html/
    depends_on:
       - db
    restart: always
    ports:
      - "8000:80"
    links:
      - db:mysql    

####################
# Setup React container
####################

  app:
    build: ./frontend/app      
    ports:
      - 3000:3000
    volumes:
      - ./frontend/app/src:/srv/app/src
      - ./frontend/app/public:/srv/app/public
    depends_on:
      - api
    links:
      - api
    restart: always
    command: npm run start

####################
# Setup Caddy container
####################
  caddy:
    build:
      context: github.com/abiosoft/caddy-docker.git
      args:
        version: 0.10.12
    volumes:
      - type: bind
        source: ./caddy/data/sites/
        target: /var/www/sites/
      - type: bind
        source: ./caddy/data/caddypath/
        target: /var/caddy/
      - type: bind
        source: ./caddy/Caddyfile
        target: /etc/Caddyfile
    environment:
      CADDYPATH: "/var/caddy"      
    ports:
      - "443:443"
      - "80:80"     
    restart: always
  
volumes:
    db_data:
